import {useEffect,useRef,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
/** React implementation of the supplied CardDeckSpread behaviour, adapted to the Odyssey design system. */
export default function CardDeck({events,onSelect}){
  const [ready,setReady]=useState(false),[selected,setSelected]=useState(null),[mode,setMode]=useState(null);const timer=useRef(null);const navigate=useNavigate();
  useEffect(()=>{const id=setTimeout(()=>setReady(true),120);return()=>{clearTimeout(id);clearTimeout(timer.current)}},[]);
  const preview=(event,index)=>{if(selected!==null)return;setSelected(index);setMode('preview');timer.current=setTimeout(()=>{onSelect(event);setSelected(null);setMode(null)},460)};
  const openFull=(event,index)=>{if(selected!==null)return;setSelected(index);setMode('route');timer.current=setTimeout(()=>navigate(`/events/${event.slug}`),560)};
  return <div className={`card-deck ${ready?'is-ready':''} ${selected!==null?'is-selecting':''} ${mode==='route'?'is-routing':''}`} role="list" aria-label="Event games"><div className="card-deck-stage" style={{'--deck-count':events.length}}>{events.map((event,index)=><article key={event.slug} role="listitem" className={`deck-card deck-card-image ${selected===index?'is-selected':''}`} style={{'--card-index':index,'--card-count':events.length,'--event-image':`url(${event.image})`}}><button type="button" className="deck-card-open" onClick={()=>preview(event,index)} aria-label={`Preview ${event.title}`}><span className="deck-card-glow"/><span className="deck-title">{event.title}</span><span className="deck-description">{event.summary}</span></button><Link className="deck-route" to={`/events/${event.slug}`} aria-label={`Open full ${event.title} event page`} onClick={e=>{e.preventDefault();e.stopPropagation();openFull(event,index)}}>View full event&nbsp; ↗</Link></article>)}</div><p className="deck-instruction">Select a card to preview · Use “View full event” for its dedicated passage</p></div>}
